[workspace]

members = [
    "compiler/oath_ast",
    "compiler/oath_diagnostics",
    "compiler/oath_diagnostics/proc_macros",
    "compiler/oath_parser",
    "compiler/oath_parser/proc_macros",
    "compiler/oath_src",
    "compiler/oath_tokenizer",
    "compiler/oath_tokenizer/keywords_puncts",
    "compiler/oath_tokenizer/proc_macros",
    "editor-server",
]
