[package]
edition = "2021"
name    = "oath_diagnostics"
version = "0.1.0"

[dependencies]
oath_diagnostics_proc_macros = { path = "proc_macros" }
oath_src                     = { path = "../oath_src" }
