[package]
edition = "2021"
name    = "oath_diagnostics"
version = "0.1.0"

[dependencies]
oath_diagnostics_macros = { path = "../oath_diagnostics_macros" }
oath_src                = { path = "../oath_src" }
