[package]
edition = "2024"
name    = "oath_diagnostics"
version = "0.1.0"

[dependencies]
dashmap       = "6.1.0"
derive-new    = "0.7.0"
derive_more   = "2.0.1"
oath_interner = { path = "../oath_interner" }
oath_src      = { path = "../oath_src" }
oath_tokens   = { path = "../oath_tokens" }
