[package]
edition = "2024"
name    = "oathc_interner"
version = "0.1.0"

[dependencies]
derive-new                 = "0.7.0"
derive_more                = { version = "2.0.1", features = [ "full" ] }
oathc_interner_proc_macros = { path = "proc_macros" }
string-interner            = "0.18.0"
