[package]
edition = "2021"
name    = "editor-server"
version = "0.1.0"

[dependencies]
oath      = { path = "../compiler/oath" }
pollster  = "0.4.0"
tokio     = { version = "1.42.0", features = [ "full" ] }
tower-lsp = "0.20.0"
