[package]
edition = "2024"
name    = "oath_highlighting"
version = "0.1.0"

[dependencies]
oath_diagnostics = { path = "../oath_diagnostics" }
oath_src         = { path = "../oath_src" }
oath_tokens      = { path = "../oath_tokens" }
