[package]
edition = "2024"
name    = "oathc_fmt"
version = "0.1.0"

[dependencies]
itertools             = "0.14.0"
oathc_diagnostics     = { path = "../oathc_diagnostics" }
oathc_fmt_proc_macros = { path = "proc_macros" }
oathc_interner        = { path = "../oathc_interner" }
